require 'ows_tasks'
require 'openlaszlo_tasks'
require 'index'

NAVDIR = File.join ENV['LPS_HOME'], 'nav'
ENV['OPENLASZLO_URL'] = nil

task :sync_navs => 'projects.xml' do
  src = 'nav.lzx'
  dst = File.join NAVDIR, 'nav.lzx'
  cp 'projects.xml', NAVDIR unless uptodate? File.join(NAVDIR, 'projects.xml'), 'projects.xml'
  sync src, dst
end

file 'label.png' do |t|
  sh "convert -background transparent label:'(enter search text here)' #{t.name}"
end

file 'red.png' do |t|
  sh "convert -background transparent -fill red label:'(enter search text here)' #{t.name}"
end

file 'projects.php' => ['index.rb', 'projects.yaml'] do |t|
  make_index t.name
end

file 'projects.xml' => ['index.rb', 'projects.yaml'] do |t|
  make_xml t.name
end

file File.join(NAVDIR, 'nav.swf') => [:sync_navs, 'red.png', 'label.png']

task :applet => ['nav.swf', :sync_navs] do |t|
  #cp t.prerequisites.first, 'nav.swf' unless uptodate? 'nav.swf', t.prerequisites.first
end

task :deploy do
  sh "ssh osteele@osteele.com 'svn up osteele.com/projects'"
end

task :default => ['projects.php', 'projects.xml', :applet]

task :clean_thumbnails do
  rm FileList('images/*-thumb.png')
end
