require 'rake/clean'
require 'ows_tasks'

def format_file src
  title = File.basename(src)
  ext = src.split('.').last
  en_language = {'js' => 'javascript', 'py' => 'python', 'java' => 'java', 'php' => 'php'}[ext]
  if en_language
    cmd = "enscript --color -E#{en_language} --language=html --title #{title} #{src} --output=-"
    result = `#{cmd}`
    #puts "#{cmd} => #{result.length}"
    return result
  end
  case ext
  when /rb|xlzx|/
    lang = {'rb' => 'ruby'}[ext] || 'xml'
    require 'syntax/convertors/html'
    s = <<-"EOF"
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
        <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
        <title>#{title}</title>
  <link href="/sources/portfolio/stylesheets/#{lang}.css" rel="stylesheet" type="text/css" />
 </head>
 <body class="#{lang}"><h1>#{title}</h1>
EOF
    s << Syntax::Convertors::HTML.for_syntax(lang).
      convert(File.open(src).read)
    s << '</body></html>'
  end
end

for file in FileList['*/**/*.*']
  target = File.join('formatted', file)
  CLOBBER << target if File.exists?(target)
  task :format => target
  task target => file do |t|
    s = format_file t.prerequisites.first
    if s
      dir = File.dirname(t.name)
      mkdir_p dir unless File.exists?(dir)
      File.open(t.name, 'w') do |f| f << s end
    end
  end
end

task 'table.html' => ['make.rb', 'index.yaml'] do |t|
  require 'make.rb'
  make_index
end

task :svn_deploy do
  sh "ssh osteele@osteele.com svn up osteele.com/sources/portfolio"
end

task :rsync_deploy => 'table.html' do |t|
  rsync ['formatted', 'table.html'], 'osteele@osteele.com:osteele.com/sources/portfolio'
end

multitask :deploy => [:svn_deploy, :rsync_deploy]
