<!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML>
<HEAD>
<TITLE>NounPhrasePatterns.py</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#1F00FF" ALINK="#FF0000" VLINK="#9900DD">
<A NAME="top">
<A NAME="file1">
<H1>PyFSA/examples/NounPhrasePatterns.py</H1>

<PRE>
<B><FONT COLOR="#A020F0">from</FONT></B> Patterns <B><FONT COLOR="#A020F0">import</FONT></B> *<B><FONT COLOR="#A020F0">from</FONT></B> PatternScanner <B><FONT COLOR="#A020F0">import</FONT></B> CategoryTestnp1 = Pattern(		<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>,		[PatternElement(tag=det_tags, quant=<FONT COLOR="#BC8F8F"><B>'?'</FONT></B>),		 PatternElement(tag=adj_tags, quant=<FONT COLOR="#BC8F8F"><B>'*'</FONT></B>),		 PatternElement(tag=noun_tags)],		CreateConstituentAction(<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>))np2 = Pattern(		<FONT COLOR="#BC8F8F"><B>'np_of_np'</FONT></B>,		[CategoryTest([<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>]),		 PatternElement(stem=[<FONT COLOR="#BC8F8F"><B>'of'</FONT></B>]),		 CategoryTest([<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>])],		CreateConstituentAction(<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>))np3 = Pattern(		<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>,		[CategoryTest([<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>]),		 PatternElement(stem=[<FONT COLOR="#BC8F8F"><B>'('</FONT></B>]),		 PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'quantity'</FONT></B>]),		 PatternElement(stem=[<FONT COLOR="#BC8F8F"><B>')'</FONT></B>])		],		CreateConstituentAction(<FONT COLOR="#BC8F8F"><B>'np'</FONT></B>))qp1 = Pattern(		<FONT COLOR="#BC8F8F"><B>'quant'</FONT></B>,		[PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'number'</FONT></B>]),		 PatternElement(stem=[<FONT COLOR="#BC8F8F"><B>'of'</FONT></B>], quant=<FONT COLOR="#BC8F8F"><B>'?'</FONT></B>),		 PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'number'</FONT></B>], quant=<FONT COLOR="#BC8F8F"><B>'?'</FONT></B>),		 PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'unit'</FONT></B>])],		CreateConstituentAction(<FONT COLOR="#BC8F8F"><B>'quantity'</FONT></B>))qp2 = Pattern(		<FONT COLOR="#BC8F8F"><B>'quant'</FONT></B>,		[PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'number'</FONT></B>]),		 PatternElement(stem=[<FONT COLOR="#BC8F8F"><B>'-'</FONT></B>]),		 PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'number'</FONT></B>]),		 PatternElement(tag=[<FONT COLOR="#BC8F8F"><B>'unit'</FONT></B>])],		CreateConstituentAction(<FONT COLOR="#BC8F8F"><B>'quantity'</FONT></B>))NOUN_PHRASE_PATTERNS = [np1, np2, np3, qp1, qp2]</PRE>
<HR>
<ADDRESS>Generated by <A HREF="http://www.iki.fi/~mtr/genscript/">GNU enscript 1.6.1</A>.</ADDRESS>
</BODY>
</HTML>
