<div class="sidetitle">Reading</div>

<div class="side">
<div class="subtitle">Current</div>
<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0802137989/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="A Good Scent from a Strange Mountain: Stories, by Robert Olen Butler">
<img src="http://images.amazon.com/images/P/0802137989.01.THUMBZZZ.jpg" border="0" alt="A Good Scent from a Strange Mountain: Stories, by Robert Olen Butler" style="float:left">
<span class="booktitle">A Good Scent from a Strange Mountain</span><br /><span class="author">Robert Olen Butler</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0262660717/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Basic Category Theory for Computer Scientists (Foundations of Computing), by Benjamin C. Pierce">
<img src="http://images.amazon.com/images/P/0262660717.01.THUMBZZZ.jpg" border="0" alt="Basic Category Theory for Computer Scientists (Foundations of Computing), by Benjamin C. Pierce" style="float:left">
<span class="booktitle">Basic Category Theory</span><br /><span class="author">Benjamin C. Pierce</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0262581469/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Cognition in the Wild, by Edwin Hutchins">
<img src="http://images.amazon.com/images/P/0262581469.01.THUMBZZZ.jpg" border="0" alt="Cognition in the Wild, by Edwin Hutchins" style="float:left">
<span class="booktitle">Cognition in the Wild</span><br /><span class="author">Edwin Hutchins</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0198721943/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Egypt, Greece and Rome: Civilizations of the Ancient Mediterranean, by Charles Freeman">
<img src="http://images.amazon.com/images/P/0198721943.01.THUMBZZZ.jpg" border="0" alt="Egypt, Greece and Rome: Civilizations of the Ancient Mediterranean, by Charles Freeman" style="float:left">
<span class="booktitle">Egypt, Greece and Rome</span><br /><span class="author">Charles Freeman</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0962813702/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Kanji Pict-O-Graphix: Over 1,000 Japanese Kanji and Kana Mnemonics, by Michael Rowley">
<img src="http://images.amazon.com/images/P/0962813702.01.THUMBZZZ.jpg" border="0" alt="Kanji Pict-O-Graphix: Over 1,000 Japanese Kanji and Kana Mnemonics, by Michael Rowley" style="float:left">
<span class="booktitle">Kanji Pict-o-Graphix</span><br /><span class="author">Michael Rowley</span></a>
<br clear="all" />

</div>
















<div class="subtitle">Recent</div>










<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0786867175/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Leap of Faith: Memoirs of an Unexpected Life, by Queen Noor">
<img src="http://images.amazon.com/images/P/0786867175.01.THUMBZZZ.jpg" border="0" alt="Leap of Faith: Memoirs of an Unexpected Life, by Queen Noor" style="float:left">
<span class="booktitle">Leap of Faith</span><br /><span class="author">Queen Noor</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0743421922/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Look to Windward, by Iain M. Banks">
<img src="http://images.amazon.com/images/P/0743421922.01.THUMBZZZ.jpg" border="0" alt="Look to Windward, by Iain M. Banks" style="float:left">
<span class="booktitle">Look to Windward</span><br /><span class="author">Iain M. Banks</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/076530418X/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="Stories of Your Life and Others, by Ted Chiang">
<img src="http://images.amazon.com/images/P/076530418X.01.THUMBZZZ.jpg" border="0" alt="Stories of Your Life and Others, by Ted Chiang" style="float:left">
<span class="booktitle">Stories of Your Life</span><br /><span class="author">Ted Chiang</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0066212537/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="The Birthday of the World: And Other Stories, by Ursula K. Le Guin">
<img src="http://images.amazon.com/images/P/0066212537.01.THUMBZZZ.jpg" border="0" alt="The Birthday of the World: And Other Stories, by Ursula K. Le Guin" style="float:left">
<span class="booktitle">The Birthday of the World</span><br /><span class="author">Ursula K. Le Guin</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0312848706/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="The Golden Age: A Romance of the Far Future, by John C. Wright">
<img src="http://images.amazon.com/images/P/0312848706.01.THUMBZZZ.jpg" border="0" alt="The Golden Age: A Romance of the Far Future, by John C. Wright" style="float:left">
<span class="booktitle">The Golden Age</span><br /><span class="author">John C. Wright</span></a>
<br clear="all" />

</div>


<div class="book">



<a href="http://www.amazon.com/exec/obidos/ASIN/0765304325/oliversteele-20?dev-t=DKJWKG3KHJF2B%26camp=2025%26link_code=xm2" target="_"blank title="The Phoenix Exultant: or, Dispossessed in Utopia, by John C. Wright">
<img src="http://images.amazon.com/images/P/0765304325.01.THUMBZZZ.jpg" border="0" alt="The Phoenix Exultant: or, Dispossessed in Utopia, by John C. Wright" style="float:left">
<span class="booktitle">The Phoenix Exultant</span><br /><span class="author">John C. Wright</span></a>
<br clear="all" />

</div>



</div>
