<?php
// $Id: commentmail.install,v 1.1 2007/02/10 17:27:31 timcn Exp $

function commentmail_update_1() {
  $ret = array();

  variable_set('commentmail_mode', variable_get('commentmail_opt', 'approval'));
  variable_del('commentmail_opt');

  return $ret;
}

function commentmail_uninstall() {
  variable_del('commentmail_to');
  variable_del('commentmail_mode');
  variable_del('commentmail_mail_approve');
  variable_del('commentmail_mail_notify');
}