<?php
// $Id$

function my_essays($cat) {
    $result = db_query(db_rewrite_sql('select distinct(n.nid), n.title, ua.dst from node n inner join term_node tn using (nid) inner join term_data td on (tn.tid=td.tid) inner join term_node tn2 using (nid) inner join term_data td2 on (tn2.tid=td2.tid) inner join vocabulary v on (v.vid=td.vid) left join url_alias ua on (ua.src=concat("node/", n.nid)) where v.name = "Categories" and td.name in ("Essays","Tips") and td2.name="%s" and n.status order by n.created desc;'), $cat);
	echo('<ul>');
    while ($item = db_fetch_object($result)) {
		echo('<li><a href="/'.$item->dst.'">'.$item->title.'</a></li>');
	}
	echo('</ul>');
}