require 'ows_tasks'

task 'docs/textcanvas.php' => ['textcanvas.js', 'Rakefile'] do |t|
    jsrdoc 'textcanvas.js', t.name, 'TextCanvas'
end

task 'docs/readable.php' => ['readable.js', 'Rakefile'] do |t|
    jsrdoc 'readable.js', t.name, 'Readable'
end

task 'docs/inline-console.php' => ['inline-console.js', 'Rakefile'] do |t|
    jsrdoc 'inline-console.js', t.name, 'Inline Console'
end

task :docs => 'docs/readable.php'
task :docs => 'docs/textcanvas.php'
task :docs => 'docs/inline-console.php'
