require 'ows_tasks'
require 'openlaszlo_tasks'

APPLET_SWF = File.expand_path('~/laszlo/lps-dev/reanimator/rematch.swf')

task :applet => APPLET_SWF

task :clear_cache do
  rm_f FileList['cache/*']
end

task :clear_remote_cache do
  sh "ssh osteele@osteele.com 'rm -rf osteele.com/tools/reanimator/cache/*'"
end

task :deploy => APPLET_SWF do |t|
  rsync t.prerequisites, 'osteele@osteele.com:osteele.com/tools/reanimator'
end

task :default => :deploy
