require 'ows_tasks'
require 'openlaszlo_tasks'

tf = File.expand_path('~/laszlo/lps-dev/reanimator/rematch.swf')
#file 'reanimator.swf' => [tf, 'json.js']+FileList['*.lzx'] do |t|
#  cp tf, t.name
#end

task :clear_cache do
  rm_f FileList['cache/*']
end

task :clear_remote_cache do
  sh "ssh osteele@osteele.com 'rm -rf osteele.com/tools/reanimator/cache/*'"
end

task :deploy => tf do |t|
  rsync t.prerequisites, 'osteele@osteele.com:osteele.com/tools/reanimator'
end

task :default => :deploy
