require 'ows_tasks'
require 'openlaszlo_tasks'

tf = File.expand_path('~/laszlo/lps-dev/rematch/rematch.swf')
file 'rematch.swf' => [tf, 'json.js']+FileList['*.lzx'] do |t|
  cp tf, t.name
end

task :clear_cache do
  rm_f FileList['cache/*']
end

task :clear_remote_cache do
  sh "ssh osteele@osteele.com 'rm -rf osteele.com/tools/rematch/cache/*'"
end

task :deploy => ['rematch.swf'] do |t|
  rsync t.prerequisites+['index.php']+FileList['*.py'], 'osteele@osteele.com:osteele.com/tools/rematch'
end
