<h2>About</h2>

<div class="side">
<a href="http://osteele.com/blog.html" style="color: inherit">Languages of the real and artificial</a> is where Oliver Steele explores programming languages, software development, math, and education.
</div>

<h2>Recent Comments</h2>
<ul>
<li>
<a href="http://www.osteele.com/archives/2003/10/the_virtual_computer_company.html">The Virtual Computer Company</a>
(1 comments)
<li>
<a href="http://www.osteele.com/archives/2003/10/recount.html">Re-count</a>
(3 comments)
<li>
<a href="http://www.osteele.com/archives/2003/08/test_versus_type.html">Test versus Type</a>
(21 comments)
<li>
<a href="http://www.osteele.com/archives/2003/07/in_memoriam_instant_update.html">In Memoriam: Instant Update</a>
(4 comments)
<li>
<a href="http://www.osteele.com/archives/2003/06/behr_color_center.html">Behr Color Center</a>
(5 comments)

</ul-->

<h2>Recent Entries</h2>

<div class="side">
<a href="http://www.osteele.com/archives/2004/04/pywordnet_20.html"><strong>&laquo; </strong>PyWordNet 2.0</a><br />
<a href="http://www.osteele.com/archives/2004/04/ingrediants_and_isochems.html"><strong>&laquo; </strong>Ingrediants and Isochems</a><br />
<a href="http://www.osteele.com/archives/2004/03/classes_and_prototypes.html"><strong>&laquo; </strong>Classes and Prototypes</a><br />
<a href="http://www.osteele.com/archives/2004/03/optimizing_for_broadband.html"><strong>&laquo; </strong>Optimizing for Broadband</a><br />
<a href="http://www.osteele.com/archives/2003/10/recount.html"><strong>&laquo; </strong>Re-count</a><br />
<a href="http://www.osteele.com/archives/2003/10/the_virtual_computer_company.html"><strong>&laquo; </strong>The Virtual Computer Company</a><br />
<a href="http://www.osteele.com/archives/2003/10/laszlo_booklist_application.html"><strong>&laquo; </strong>Laszlo Booklist Application</a><br />
<a href="http://www.osteele.com/archives/2003/09/before_teletext.html"><strong>&laquo; </strong>Before Teletext</a><br />
<a href="http://www.osteele.com/archives/2003/08/a_taxonomy_of_comments.html"><strong>&laquo; </strong>A Taxonomy of Comments</a><br />
<a href="http://www.osteele.com/archives/2003/08/test_versus_type.html"><strong>&laquo; </strong>Test versus Type</a><br />

</div>

<h2>Subjects</h2>

<div class="side">
<a href="http://www.osteele.com/archives/categories/education/index.html"><strong>&laquo; </strong>Education</a><br />
<a href="http://www.osteele.com/archives/categories/family/index.html"><strong>&laquo; </strong>Family</a><br />
<a href="http://www.osteele.com/archives/categories/health/index.html"><strong>&laquo; </strong>Health</a><br />
<a href="http://www.osteele.com/archives/categories/inventions/index.html"><strong>&laquo; </strong>Inventions</a><br />
<a href="http://www.osteele.com/archives/categories/laszlo/index.html"><strong>&laquo; </strong>Laszlo</a><br />
<a href="http://www.osteele.com/archives/categories/linguistics/index.html"><strong>&laquo; </strong>Linguistics</a><br />
<a href="http://www.osteele.com/archives/categories/mathematics/index.html"><strong>&laquo; </strong>Mathematics</a><br />
<a href="http://www.osteele.com/archives/categories/software/index.html"><strong>&laquo; </strong>Software</a><br />
<a href="http://www.osteele.com/archives/categories/systems/index.html"><strong>&laquo; </strong>Systems</a><br />
<a href="http://www.osteele.com/archives/categories/technology/index.html"><strong>&laquo; </strong>Technology</a><br />

</div>

<h2>Blogroll</h2>

<script language="javascript" type="text/javascript" src="http://www.mylaszlo.com/cgi-bin/blogbox?f=display&amp;bid=3af461e9b9d16676535e2c5af2fa551a"></script>

<div style="display:none">
Laszlo Blogs
<a href="http://www.davidtemkin.com/">David Temkin</a><br />
<a href="http://www.ultrasaurus.com/">Ultrasaurus</a><br />
<a href="http://www.laszlosystems.com/~adam/blog/">Adam Wolff</a><br />
<a href="http://pt.withy.org/ptalk/">ptalk</a><br />
<a href="http://lyndonwong.blogspot.com/">Trench Talk</a><br />
<a href="http://www.wetmachine.com/">Wetmachine</a><br />

Software Blogs
<a href="http://enthusiasm.cozy.org/">Ascription is an anathema to any enthusiasm</a><br />
<a href="http://usefulinc.com/edd/blog">Behind the Times</a><br />
<a href="http://www.estherderby.com/weblog/blogger.html">Esther Derby</a><br />
<a href="http://www.testing.com/cgi-bin/blog">Exploration Through Example</a><br />
<a href="http://www.joelonsoftware.com/">Joel on Software</a><br />
<a href="http://weblog.infoworld.com/udell/">Jon Udell</a><br />
<a href="http://patricklogan.blogspot.com/">Making it Stick</a><br />
<a href="http://www.jroller.com/page/ceperez">Manageability</a><br />
<a href="http://gigavolt.net/blog">Potential Differences</a><br />
<a href="http://www.sauria.com/blog">Ted Leung</a><br />
<a href="http://www.ventureblog.com/">VentureBlog</a><br />

Language Blogs
<a href="http://lambda.weblogs.com/">Lambda the Ultimate</a><br />
<a href="http://lemonodor.com/">Lemonodor</a><br />



</div>

<div style="display: none">
<!--?php include("/includes/books/index.inc");?-->
</div>

    <h2>Other Links</h2>
  <ul>
          <li><a href="http://www.haskell.org"><strong>&laquo; </strong>Haskell home page</a></li>
            <li><a href="http://www.paulgraham.com/"><strong>&laquo; </strong>Paul Graham's site</a></li>
            <li><a href="http://norvig.com"><strong>&laquo; </strong>Peter Norvig's site</a></li>
            <li><a href="http://www.python.org"><strong>&laquo; </strong>Python home page</a></li>
      
  </ul>
  


<h2>Search this site</h2>
 
<div class="side">
<form method="get" action="http://osteele.com/mt/mt-search.cgi">
<input type="hidden" name="IncludeBlogs" value="1" />
<label for="search" accesskey="4">Search this site:</label><br />
<input id="search" name="search" size="20" /><br />
<input type="submit" value="Search" />
</form>
</div>

<h2>Syndication</h2>
 
<div class="side">
<a href="http://osteele.com/index.rdf" class="feedbox"><span class="xmlbox">XML</span> Summaries</a><br />

<a href="http://osteele.com/index-complete.rdf" class="feedbox"><span class="xmlbox">XML</span> Articles</a><br />

<a href="http://osteele.com/index-software.rdf" class="feedbox"><span class="xmlbox">XML</span> Software articles</a><br />
</div>

<h2>More</h2>

<div class="side">
<a href="javascript:void(rollpop=window.open('http://www.blogrolling.com/add_links_pop.phtml?u=http://osteele.com&amp;t=Oliver Steele','rollit','scrollbars=no,width=475,height=350,left=75,top=175,status=yes,resizable=yes'));rollpop.focus();">Blogroll Me!</a><br />

Copyright &copy;2003-2004 by Oliver Steele.  <a href="http://creativecommons.org/licenses/by-nd-nc/1.0">Some rights reserved.</a><br />

<a href="http://osteele.com/contact.html" class="contactbox">Contact</a><br />

<!--a href="http://www.blogshares.com/blogs.php?blog=http%3A%2F%2Fwww.osteele.com%2F&amp;user=11024"><img src="http://www.blogshares.com/images/blogshares.jpg" alt="Listed on BlogShares" width="117" height="23"/></a-->
</div>

<div class="powered">
Powered by<br /><a href="http://www.movabletype.org">Movable Type 1.2</a><br />    
</div>
