<!DOCTYPE html PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML>
<HEAD>
<TITLE>colors.js</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000" LINK="#1F00FF" ALINK="#FF0000" VLINK="#9900DD">
<A NAME="top">
<A NAME="file1">
<H1>expialidocious/colors.js</H1>

<PRE>
<I><FONT COLOR="#B22222">/*
Copyright 2005-2006 Oliver Steele.  Some rights reserved.
$LastChangedDate: 2006-01-07 15:24:44 -0500 (Sat, 07 Jan 2006) $

This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 2.5 License:
http://creativecommons.org/licenses/by-nc-sa/2.5/.
*/</FONT></I>

<B><FONT COLOR="#A020F0">function</FONT></B> <B><FONT COLOR="#0000FF">long2css</FONT></B>(n) {
  <B><FONT COLOR="#A020F0">var</FONT></B> a = <FONT COLOR="#BC8F8F"><B>&quot;0123456789ABCDEF&quot;</FONT></B>;
  <B><FONT COLOR="#A020F0">var</FONT></B> s = <FONT COLOR="#BC8F8F"><B>'#'</FONT></B>;
  <B><FONT COLOR="#A020F0">for</FONT></B> (<B><FONT COLOR="#A020F0">var</FONT></B> i = 24; (i -= 4) &gt;= 0; ) {
    s += a.charAt((n&gt;&gt;i) &amp; 0xf);
  }
  <B><FONT COLOR="#A020F0">return</FONT></B> s;
}
    
<B><FONT COLOR="#A020F0">function</FONT></B> <B><FONT COLOR="#0000FF">interpolateColors</FONT></B>(a, b, s) {
  <B><FONT COLOR="#A020F0">var</FONT></B> n = 0;
  <B><FONT COLOR="#A020F0">for</FONT></B> (<B><FONT COLOR="#A020F0">var</FONT></B> i = 24; (i -= 8) &gt;= 0; ) {
    <B><FONT COLOR="#A020F0">var</FONT></B> ca = (a &gt;&gt; i) &amp; 0xff;
    <B><FONT COLOR="#A020F0">var</FONT></B> cb = (b &gt;&gt; i) &amp; 0xff;
    <B><FONT COLOR="#A020F0">var</FONT></B> cc = <FONT COLOR="#DA70D6"><B>Math</FONT></B>.floor(ca*(1-s) + cb*s);
    n |= cc &lt;&lt; i;
  }
  <B><FONT COLOR="#A020F0">return</FONT></B> n;
}
</PRE>
<HR>
<ADDRESS>Generated by <A HREF="http://www.iki.fi/~mtr/genscript/">GNU enscript 1.6.1</A>.</ADDRESS>
</BODY>
</HTML>
